site_name: Marcelo Acosta Cavalero
site_author: Marcelo Acosta Cavalero
site_description: >-
  Site Description
repo_name: Github
repo_url: https://github.com/marceloacosta
site_url: http://www.marcelops.com/
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2025 Marcelo Acosta Cavalero
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
    logo: material/cog-outline
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: jxnl 
      repo: instructor
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
nav:
  - Sobre mí: index.md
  - Escritos:
      - Blog Overview: blog/index.md
      - Niveles de RAG: blog/posts/niveles-rag-1.md
      - Agentes Inteligentes: blog/posts/agentes.md
      - Escalamiento Responsable: blog/posts/escalamiento-responsable-ia.md
      - Evaluaciones IA: blog/posts/evaluaciones-ia.md
      - IA en tu empresa: blog/posts/ia-en-tu-empresa.md
      - Programadores y IA: blog/posts/programadores-y-ia.md
      - Trampa del conocimiento instantáneo: blog/posts/trampa-conocimiento-instantaneo.md
  - Contacto: https://calendly.com/macosta-zircon/


plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: alphabetical
            allow_inspection: true
            show_bases: true
  - blog:
      blog_dir: blog
      post_dir: blog/posts
      post_date_format: yyyy/MM/dd
      blog_toc: true
      archive: true
      categories: true

extra:
  analytics:
    provider: google
    property: G-H8C0CLZTWR
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/marceloacostacavalero/
    - icon: fontawesome/brands/github
      link: https://github.com/marceloacosta
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - javascripts/analytics.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
copyright: Copyright &copy; 2025 Marcelo Acosta Cavalero
