authors:
  marceloacosta:
    name: Marcelo Acosta Cavalero
    description: >
      Consultor en IA y desarrollo de software, especializado en integración 
      práctica de tecnologías emergentes.
    avatar: https://github.com/marceloacosta.png
    url: https://www.linkedin.com/in/marceloacostacavalero/ 