authors:
  me:
    name: Marcelo Acosta Cavalero
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/4666796
    url: https://marceloacosta.github.io/
    linkedin: https://www.linkedin.com/in/marceloacostacavalero/