name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [main]  # or 'master' if that's your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout blog repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-doc.txt

      - name: Build site
        run: mkdocs build

      - name: Deploy to GitHub Pages repo
        run: |
          cd site
          touch .nojekyll
          echo "www.marcelops.com" > CNAME
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/marceloacosta/marceloacosta.github.io.git
          git checkout -b main
          git add .
          git commit -m "Deploy from blog repo"
          git push -f origin main
